import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@styles/global.scss';
import ServerProvider from '@/app/Voiture/ServerContext';
import { ReservationProvider } from '@/app/Voiture/ReservationHourContext';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
      <ServerProvider>
        <ReservationProvider>
          {children}
        </ReservationProvider>
      </ServerProvider>
      </body>
    </html>
  );
}
